[application]
name = "Diesel"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "Diesel"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]
index_on_404 = false

[web.resource]
style = ["tailwind.css", "extra.css"]

[web.resource.dev]
